local be = require("api.bus_events")
local T = be.translate

describe("api.bus_events", function()
  it("audio engine events carry the stream id and position", function()
    assert_eq(T("/j/audio/input/playing", '{"id":7}'), { type = "audio.playing", id = 7 })
    assert_eq(T("/j/audio/input/ended", '{"id":3}'), { type = "audio.ended", id = 3 })
    assert_eq(T("/j/audio/input/position", '{"id":7,"pos":12345}'), { type = "audio.position", id = 7, ms = 12345 })
    assert_nil(T("/j/audio/input/weird", "{}"))
  end)

  it("nfc: uid + character code, removal, written, and malformed payloads", function()
    assert_eq(T("/j/nfc/input/tag", "0433366ae74c81,106"), { type = "nfc.tag", uid = "0433366AE74C81", star_code = 262 })
    assert_eq(T("/j/nfc/input/tag", "garbage"), { type = "nfc.tag", bad = true, raw = "garbage" })
    assert_eq(T("/j/nfc/input/tag_removed", ""), { type = "nfc.removed" })
    assert_eq(T("/j/nfc/input/tag_written", "04AA"), { type = "nfc.written", uid = "04AA" })
  end)

  it("buttons, knob, power, network, bluetooth, system events, mender, v1", function()
    assert_eq(T("/j/gpio/input/next", "1"), { type = "gpio.button", button = "next", down = true })
    assert_eq(T("/j/gpio/input/circle", "0"), { type = "gpio.button", button = "circle", down = false })
    assert_eq(T("/j/gpio/input/vol_set", '{"vol":55}'), { type = "gpio.volume", percent = 55 })
    assert_nil(T("/j/gpio/input/nope", "1"))
    assert_eq(T("/j/power/input/battery_level", '{"mv":3900,"p":870,"t":31000}'), { type = "power.battery", mv = 3900, tenths = 870, mc = 31000 })
    assert_eq(T("/j/power/input/plugged_in", "1"), { type = "power.plugged", on = true })
    assert_eq(T("/j/power/input/charging", "0"), { type = "power.charging", on = false })
    local n = T("/j/esp32/input/net/sta/config", '{"ssid":"Box","bssid":"aa","ch":1,"signal":-70,"crypt":3,"stat":"success","ip":"10.0.0.2"}')
    assert_eq(n, { type = "net.status", ssid = "Box", bssid = "aa", channel = 1, signal = -70, connected = true, ip = "10.0.0.2" })
    assert_eq(T("/j/esp32/input/knobs/state", '{"volume":97,"control":2,"hp_state":1}'), { type = "knobs", volume = 97, headphones = true, control = 2 })
    assert_eq(T("/j/esp32/input/bt/state", "9"), { type = "bt.state", code = 9 })
    assert_eq(T("/j/net/dhcp/bound", ""), { type = "net.dhcp", event = "bound" })
    assert_eq(T("/j/event", "Evt.WiFi.home.connect"), { type = "system.event", name = "Evt.WiFi.home.connect" })
    assert_eq(T("/j/mender", "Download_Enter_"), { type = "mender", raw = "Download_Enter_" })
    assert_eq(T("/j/web/input/GET_STATE", "{}"), { type = "v1.cmd", name = "GET_STATE", raw = "{}" })
    assert_nil(T("/j/led/output/set_raw", "x"))
  end)

  it("chain() tries translators in order", function()
    local f = be.chain(function(t) if t == "a" then return { type = "A" } end end, be.translate)
    assert_eq(f("a", ""), { type = "A" })
    assert_eq(f("/j/event", "E"), { type = "system.event", name = "E" })
    assert_nil(f("zzz", ""))
  end)
end)
