local library = require("services.library")
local ops = library.ops
local TRASH = library.TRASH

local function lib_with(tracks, playlists, tokens)
  local l = { playlists = playlists or {}, tracks = {}, tokens = tokens or {} }
  for _, id in ipairs(tracks or {}) do l.tracks[id] = { title = "Song " .. id, filename = "/data/uploads/" .. id, duration = 10 } end
  return l
end

describe("library.ops — playlists", function()
  it("creates a playlist with a clean title, unique ids, optional character", function()
    local l = lib_with()
    local a = ops.playlist_new(l, { title = "  Comptines  " }, 100)
    local b = ops.playlist_new(l, { title = "" }, 100)
    local c = ops.playlist_new(l, { title = "X", audiobook = true, star = "Jooki.Fox" }, 100)
    assert_eq(a, "user_100"); assert_eq(b, "user_100_1"); assert_eq(c, "user_100_2")
    assert_eq(l.playlists[a].title, "Comptines")
    assert_eq(l.playlists[b].title, "Untitled Playlist")
    assert_eq(l.playlists[c], { title = "X", tracks = {}, audiobook = true, star = "Jooki.Fox" })
  end)

  it("keeps one playlist per character", function()
    local l = lib_with()
    local a = ops.playlist_new(l, { title = "A", star = "Jooki.Fox" }, 1)
    local b = ops.playlist_new(l, { title = "B" }, 2)
    assert_true(ops.link_star(l, b, "Jooki.Fox"))
    assert_nil(l.playlists[a].star); assert_eq(l.playlists[b].star, "Jooki.Fox")
    assert_eq(ops.playlist_for(l, "Jooki.Fox"), b)
    local _, err = ops.link_star(l, b, "")
    assert_eq(err.code, "invalid_argument")
    ops.unlink(l, b)
    assert_nil(ops.playlist_for(l, "Jooki.Fox"))
  end)

  it("deleting a playlist sends its tracks to Unused and forgets its radios", function()
    local l = lib_with({ "t1", "t2" })
    local p = ops.playlist_new(l, { title = "P" }, 1)
    ops.playlist_add_track(l, p, "t1")
    local s = ops.playlist_add_stream(l, p, "FIP", "https://icecast.radiofrance.fr/fip", 1)
    assert_eq(l.playlists[TRASH].tracks, { "t2" })
    assert_true(ops.playlist_delete(l, p))
    assert_eq(l.playlists[TRASH].tracks, { "t1", "t2" })
    assert_nil(l.tracks[s])
    local _, err = ops.playlist_delete(l, TRASH)
    assert_eq(err.code, "read_only")
  end)

  it("update: rename, flag, reorder, and unknown track ids are dropped", function()
    local l = lib_with({ "t1", "t2", "t3" })
    local p = ops.playlist_new(l, { title = "P" }, 1)
    ops.playlist_add_track(l, p, "t1"); ops.playlist_add_track(l, p, "t2")
    assert_true(ops.playlist_update(l, { id = p, title = " New ", audiobook = true, tracks = { "t2", "t1", "ghost" } }))
    assert_eq(l.playlists[p].title, "New"); assert_true(l.playlists[p].audiobook)
    assert_eq(l.playlists[p].tracks, { "t2", "t1" })
    local _, err = ops.playlist_update(l, { id = p, title = "  " })
    assert_eq(err.field, "title")
    assert_true(ops.playlist_update(l, { id = p, audiobook = false }))
    assert_nil(l.playlists[p].audiobook)
  end)

  it("TRASH is read-only except for deleting really unused files", function()
    local l = lib_with({ "t1", "t2" })
    local p = ops.playlist_new(l, { title = "P" }, 1)
    ops.playlist_add_track(l, p, "t1")
    local _, err = ops.playlist_update(l, { id = TRASH, title = "x" })
    assert_eq(err.message, "TRASH_READONLY")
    -- a stale page asks TRASH to keep nothing while t1 is used by P: only t2 is deleted
    local ok, extra = ops.playlist_update(l, { id = TRASH, tracks = {} })
    assert_true(ok)
    assert_eq(extra.removed_files, { "/data/uploads/t2" })
    assert_true(l.tracks.t1 ~= nil); assert_nil(l.tracks.t2); assert_nil(l.playlists[TRASH])
    local _, err2 = ops.playlist_add_track(l, TRASH, "t1")
    assert_eq(err2.code, "read_only")
  end)

  it("streams: validated url, unique ids, forgotten when no playlist uses them", function()
    local l = lib_with()
    local p = ops.playlist_new(l, { title = "P" }, 1)
    local _, err = ops.playlist_add_stream(l, p, "x", "javascript:alert(1)", 5)
    assert_eq(err.field, "url")
    local s1 = ops.playlist_add_stream(l, p, "", "http://r/a", 5)
    local s2 = ops.playlist_add_stream(l, p, "R", "http://r/a", 5)
    assert_eq(s1, "stream_5"); assert_eq(s2, "stream_5_1")
    assert_eq(l.tracks[s1].title, "http://r/a")
    ops.playlist_update(l, { id = p, tracks = { s2 } })
    assert_nil(l.tracks[s1]); assert_true(l.tracks[s2] ~= nil)
    assert_nil(l.playlists[TRASH])   -- radios never appear in Unused
  end)
end)

describe("library.ops — tracks and tokens", function()
  it("track_delete removes the track everywhere and returns its file", function()
    local l = lib_with({ "t1" })
    local p = ops.playlist_new(l, { title = "P" }, 1)
    ops.playlist_add_track(l, p, "t1")
    assert_eq(ops.track_delete(l, "t1"), "/data/uploads/t1")
    assert_eq(l.playlists[p].tracks, {})
    local _, err = ops.track_add(l, "t1", { title = "x" }); assert_nil(err)
    local _, err2 = ops.track_add(l, "t1", { title = "x" }); assert_eq(err2.code, "conflict")
  end)

  it("learn / edit / forget tokens; unknown characters are learned too", function()
    local l = lib_with()
    assert_true(ops.learn(l, "04000000F00001", "Jooki.Fox"))
    assert_true(ops.learn(l, "04000000F00001", "Jooki.Fox"))
    assert_eq(l.tokens["04000000F00001"], { starId = "Jooki.Fox", seen = 2 })
    assert_false(ops.learn(l, "bad", "Jooki.Fox"))
    assert_true(ops.learn(l, "04000000F00002", "new.abc"))
    assert_true(ops.token_edit(l, "04000000F00001", "  Dark  ", nil))
    assert_eq(l.tokens["04000000F00001"].name, "Dark")
    assert_true(ops.token_edit(l, "04000000F00001", false, "pic.png"))
    assert_nil(l.tokens["04000000F00001"].name); assert_eq(l.tokens["04000000F00001"].image, "pic.png")
    local _, err = ops.token_edit(l, "04000000F00001", 42)
    assert_eq(err.field, "name")
    assert_true(ops.token_forget(l, "04000000F00001"))
    local _, err2 = ops.token_forget(l, "04000000F00001"); assert_eq(err2.code, "not_found")
  end)

  it("forgetting a token keeps the character's playlist", function()
    local l = lib_with()
    ops.learn(l, "04000000F00001", "Jooki.Fox")
    local p = ops.playlist_new(l, { title = "P", star = "Jooki.Fox" }, 1)
    ops.token_forget(l, "04000000F00001")
    assert_eq(l.playlists[p].star, "Jooki.Fox")
  end)
end)

describe("library.ops — normalise (boot)", function()
  it("migrates per-token links, drops bad tokens, repairs track lists, rebuilds Unused", function()
    local l = lib_with({ "t1", "t2" }, {
      user_1 = { title = "Old", tagId = "04000000B00001", tracks = { "t1", "ghost" } },
      user_2 = { title = "Fox", star = "Jooki.Fox", tracks = {} },
      user_3 = { title = "FoxTag", tagId = "04000000F00001", tracks = {} },
      user_4 = { title = "Flat", star = "Jooki.Flat.Dragon", tracks = {} },
      TRASH = { title = "Unused tracks", star = "Jooki.Whale", tracks = { "zzz" } },
    }, { ["04000000B00001"] = { starId = "Jooki.Black.Dragon", seen = 1 }, ["04000000F00001"] = { starId = "Jooki.Fox", seen = 1 }, bad = { starId = "x" } })
    l.tracks.orphan = { title = "r", filename = "http://x", isUrl = true }
    local changed = ops.normalise(l)
    assert_eq(changed, { playlists = true, tracks = true, tokens = true })
    assert_eq(l.playlists.user_1.star, "Jooki.Black.Dragon"); assert_nil(l.playlists.user_1.tagId)
    assert_eq(l.playlists.user_1.tracks, { "t1" })
    assert_eq(l.playlists.user_2.star, "Jooki.Fox"); assert_nil(l.playlists.user_3.star); assert_nil(l.playlists.user_3.tagId)
    assert_eq(l.playlists.user_4.star, "Jooki.Flat")
    assert_nil(l.playlists[TRASH].star)
    assert_eq(l.playlists[TRASH].tracks, { "t2" })
    assert_nil(l.tokens.bad); assert_nil(l.tracks.orphan)
    assert_eq(ops.normalise(l), { playlists = false, tracks = false, tokens = false })
  end)
end)

describe("library handlers", function()
  local api = require("api.v2")
  local dispatch = require("kernel.dispatch")
  local json = require("vendor.json")
  before_each(function()
    api.reset(); dispatch.reset({})
    library.install(api, dispatch)
  end)

  it("boot normalises and writes only what changed", function()
    local r = library.on_boot({ config = { data_dir = "/d" } }, { type = "boot", library = { playlists = { a = { title = "A", tagId = "04000000F00001" } }, tracks = {}, tokens = { ["04000000F00001"] = { starId = "Jooki.Fox" } } } })
    assert_eq(r.state.library.playlists.a.star, "Jooki.Fox")
    assert_eq(#r.commands, 1); assert_eq(r.commands[1].path, "/d/playlists.json")
  end)

  it("api commands mutate a copy, persist, and reply with typed errors", function()
    local doc = { config = { data_dir = "/d" }, library = { playlists = {}, tracks = { t1 = { title = "x", filename = "/d/uploads/t1" } }, tokens = {} } }
    local ev = api.translate(api.TOPIC_CMD, json.encode({ v = 2, id = "1", type = "playlist.new", payload = { title = "Soir" } }))
    ev.wall = 42
    local r = api.handle(doc, ev)
    assert_eq(r.state.library.playlists.user_42.title, "Soir")
    assert_true(doc.library.playlists.user_42 == nil, "the original document is not mutated")
    assert_eq(r.commands[1].kind, "files.write"); assert_eq(r.commands[#r.commands].payload.ok, true)
    doc.library = r.state.library
    ev = api.translate(api.TOPIC_CMD, json.encode({ v = 2, id = "2", type = "playlist.update", payload = { id = "TRASH", title = "no" } }))
    r = api.handle(doc, ev)
    assert_eq(r.commands[#r.commands].payload.error.code, "read_only")
    ev = api.translate(api.TOPIC_CMD, json.encode({ v = 2, id = "3", type = "playlist.update", payload = { id = "user_42", tracks = 5 } }))
    r = api.handle(doc, ev)
    assert_eq(r.commands[#r.commands].payload.error.field, "payload.tracks")
  end)
end)
