local timers = require("kernel.timers")

describe("kernel.timers", function()
  before_each(function() timers.reset() end)

  it("fires a periodic timer at each period, in order", function()
    timers.every("b", 2, 0)
    timers.every("a", 2, 0)
    timers.every("slow", 5, 0)
    assert_eq(timers.due(1), {})
    assert_eq(timers.due(2), { { type = "timer", name = "a", now = 2 }, { type = "timer", name = "b", now = 2 } })
    assert_eq(timers.next_due(2), 2)
    assert_eq(timers.due(5), { { type = "timer", name = "a", now = 5 }, { type = "timer", name = "b", now = 5 }, { type = "timer", name = "slow", now = 5 } })
  end)

  it("never fires twice in a row after a long stall", function()
    timers.every("t", 1, 0)
    local ev = timers.due(10)
    assert_eq(#ev, 1)
    assert_eq(timers.next_due(10), 1)
  end)

  it("one-shot timers fire once and can be replaced or cancelled", function()
    timers.once("x", 3, 0)
    assert_true(timers.pending("x"))
    timers.once("x", 5, 0)
    assert_eq(timers.due(3), {})
    assert_eq(#timers.due(5), 1)
    assert_false(timers.pending("x"))
    timers.once("y", 1, 0)
    timers.cancel("y")
    assert_eq(timers.due(9), {})
    assert_nil(timers.next_due(9))
  end)

  it("next_due never goes negative", function()
    timers.every("t", 1, 0)
    assert_eq(timers.next_due(50), 0)
  end)
end)
