local tokens = require("services.tokens")

local function doc_with(playlists, toks)
  return { config = { data_dir = "/d" }, nfc = {}, library = { playlists = playlists or {}, tracks = {}, tokens = toks or {} } }
end
local function emitted(r, etype)
  for _, c in ipairs(r.commands) do if c.kind == "emit" and c.event.type == etype then return c.event end end
  return nil
end

describe("services.tokens", function()
  it("maps codes to characters, unknown codes to new.<hex>, none for 0xFFFF", function()
    assert_eq(tokens.star_name(262), "Jooki.Black.Dragon")
    assert_eq(tokens.star_name(528), "G2.Orange")
    assert_eq(tokens.star_name(1030), "test.6")
    assert_eq(tokens.star_name(4095), "new.fff")
    assert_nil(tokens.star_name(65535)); assert_nil(tokens.star_name(nil))
  end)

  it("a known character with a playlist: learns the token, sets nfc, requests playback", function()
    local doc = doc_with({ user_1 = { title = "P", star = "Jooki.Black.Dragon", tracks = {} } })
    local r = tokens.on_tag(doc, { type = "nfc.tag", uid = "04000000B00001", star_code = 262 })
    assert_eq(r.state.nfc, { starId = "Jooki.Black.Dragon", tagId = "04000000B00001" })
    assert_eq(r.state.library.tokens["04000000B00001"], { starId = "Jooki.Black.Dragon", seen = 1 })
    assert_eq(r.commands[1].kind, "files.write"); assert_eq(r.commands[1].path, "/d/tokens.json")
    assert_eq(emitted(r, "system.event").name, "Evt.Character.Detect")
    assert_eq(emitted(r, "playback.request"), { type = "playback.request", playlist = "user_1", source = "token" })
    assert_true(doc.library.tokens["04000000B00001"] == nil, "original document untouched")
  end)

  it("a foreign tag (amiibo, sticker): its own character tag.<uid>, learned, not on the Jooki, then starts its playlist", function()
    local r = tokens.on_tag(doc_with({}), { type = "nfc.tag", uid = "046158B2661290", foreign = true })
    assert_nil(r.state.nfc)
    assert_eq(r.state.library.tokens["046158B2661290"], { starId = "tag.046158B2661290", seen = 1 })
    assert_nil(emitted(r, "playback.request"))
    assert_eq(emitted(r, "system.event").name, "Evt.Character.Detect.Empty")
    local doc = doc_with({ user_1 = { title = "Mario", star = "tag.046158B2661290", tracks = {} } }, r.state.library.tokens)
    local r2 = tokens.on_tag(doc, { type = "nfc.tag", uid = "046158B2661290", foreign = true })
    assert_eq(emitted(r2, "playback.request"), { type = "playback.request", playlist = "user_1", source = "token" })
    assert_eq(r2.state.library.tokens["046158B2661290"].seen, 2)
  end)

  it("flat tokens (one code for all of them): each one is its own character flat.<uid>, on the Jooki like a token", function()
    local doc = doc_with({ user_1 = { title = "Chat", star = "flat.04A1B2C3D49C41", tracks = {} },
                           user_2 = { title = "Éléphant", star = "flat.04A1B2C3D477A0", tracks = {} } })
    local r = tokens.on_tag(doc, { type = "nfc.tag", uid = "04A1B2C3D49C41", star_code = 512 })
    assert_eq(r.state.nfc, { starId = "flat.04A1B2C3D49C41", tagId = "04A1B2C3D49C41" })
    assert_eq(r.state.library.tokens["04A1B2C3D49C41"], { starId = "flat.04A1B2C3D49C41", seen = 1 })
    assert_eq(emitted(r, "playback.request").playlist, "user_1")
    r = tokens.on_tag(doc, { type = "nfc.tag", uid = "04A1B2C3D477A0", star_code = 512 })
    assert_eq(emitted(r, "playback.request").playlist, "user_2")
    -- taking it off pauses, as with any Jooki token
    assert_eq(emitted(tokens.on_removed({ nfc = r.state.nfc }), "playback.pause_request").source, "token")
  end)

  it("a flat token without a playlist of its own plays the one of all the flat tokens; the Thank-you token too", function()
    local doc = doc_with({ user_1 = { title = "Tous les jetons plats", star = "Jooki.Flat", tracks = {} },
                           user_2 = { title = "Le mien", star = "flat.04A1B2C3D49C41", tracks = {} },
                           user_3 = { title = "Merci", star = "Jooki.ThankYou", tracks = {} } })
    assert_eq(emitted(tokens.on_tag(doc, { type = "nfc.tag", uid = "04A1B2C3D41E07", star_code = 512 }), "playback.request").playlist, "user_1")
    assert_eq(emitted(tokens.on_tag(doc, { type = "nfc.tag", uid = "04A1B2C3D49C41", star_code = 512 }), "playback.request").playlist, "user_2")
    local r = tokens.on_tag(doc, { type = "nfc.tag", uid = "0400000000AA01", star_code = 260 })
    assert_eq(r.state.nfc.starId, "thanks.0400000000AA01")
    assert_eq(emitted(r, "playback.request").playlist, "user_3")
    assert_eq(tokens.own_star("Jooki.Fox", "04000000F00001"), "Jooki.Fox")
  end)

  it("a second token of the same character starts the same playlist (character rule)", function()
    local doc = doc_with({ user_1 = { title = "P", star = "Jooki.Black.Dragon", tracks = {} } }, { ["04000000B00001"] = { starId = "Jooki.Black.Dragon", seen = 3 } })
    local r = tokens.on_tag(doc, { type = "nfc.tag", uid = "04000000B00099", star_code = 262 })
    assert_eq(emitted(r, "playback.request").playlist, "user_1")
  end)

  it("a character without playlist: learned, no playback, 'empty' event", function()
    local doc = doc_with({})
    local r = tokens.on_tag(doc, { type = "nfc.tag", uid = "04000000F00001", star_code = 257 })
    assert_nil(emitted(r, "playback.request"))
    assert_eq(emitted(r, "system.event").name, "Evt.Character.Detect.Empty")
    assert_eq(r.state.library.tokens["04000000F00001"].starId, "Jooki.Fox")
  end)

  it("system tags are routed, not learned; bad tags only log", function()
    local doc = doc_with({})
    local r = tokens.on_tag(doc, { type = "nfc.tag", uid = "04000000000001", star_code = 773 })
    assert_eq(emitted(r, "system.tag").name, "sys.toy_safe_on")
    assert_nil(r.state.library)
    r = tokens.on_tag(doc, { type = "nfc.tag", bad = true, raw = "x" })
    assert_nil(r.state); assert_eq(r.commands[1].kind, "log")
  end)

  it("removing the token clears nfc and asks for a pause; the record tag stops recording", function()
    local r = tokens.on_removed({ nfc = { starId = "Jooki.Fox", tagId = "04" } })
    assert_eq(r.state.nfc, {})
    assert_eq(emitted(r, "playback.pause_request").source, "token")
    r = tokens.on_removed({ nfc = { starId = "sys.record", tagId = "04" } })
    assert_eq(emitted(r, "system.tag").name, "sys.record.stop")
  end)

  it("a picture for a token: the upload moves to artwork/, the token keeps its address with a cache key", function()
    local doc = doc_with({}, { ["046158B2661290"] = { starId = "tag.046158B2661290", seen = 2 } })
    local r = tokens.on_set_image(doc, { tagId = "046158B2661290", uploadId = "4242" })
    assert_eq(r.commands[1].kind, "files.rename")
    assert_eq(r.commands[1].from, "/d/uploads/upload_4242"); assert_eq(r.commands[1].to, "/d/artwork/tok_046158B2661290.png")
    assert_eq(r.commands[1].reply, "tokens.image_moved")
    r = tokens.on_image_moved(doc, { ok = true, size = 9876, ref = r.commands[1].ref })
    assert_eq(r.state.library.tokens["046158B2661290"].image, "/artwork/tok_046158B2661290.png?v=9876")
    assert_eq(r.commands[1].kind, "files.write"); assert_eq(r.commands[1].path, "/d/tokens.json")
    assert_true(doc.library.tokens["046158B2661290"].image == nil, "original document untouched")
  end)

  it("a picture for an unknown token or a bad upload id: the temp file goes, the page is told", function()
    local doc = doc_with({}, {})
    local r = tokens.on_set_image(doc, { tagId = "046158B2661290", uploadId = "7" })
    assert_eq(r.commands[1].kind, "files.remove"); assert_eq(r.commands[1].path, "/d/uploads/upload_7")
    assert_eq(emitted(r, "user.message").messageType, "TOKEN_IMAGE_FAIL")
    r = tokens.on_set_image(doc, { tagId = "046158B2661290", uploadId = "../etc" })
    assert_eq(r.commands[1].kind, "files.remove"); assert_nil(emitted(r, "nothing"))
    assert_eq(emitted(r, "user.message").extra.err, "invalid uploadId")
    r = tokens.on_image_moved(doc, { ok = false, err = "ENOENT", ref = { uid = "046158B2661290", temp = "/d/uploads/upload_9" } })
    assert_eq(r.commands[1].kind, "files.remove"); assert_eq(r.commands[1].path, "/d/uploads/upload_9")
  end)
end)
