"""End-to-end tests of the new web UI against the bench (real Lua app + mosquitto)."""
import sys, time, json, os, subprocess
from playwright.sync_api import sync_playwright
from jk import Jooki, PAGE
LUA = os.environ.get("PLAYER_LUA", "player.patched.lua")
URL = PAGE
R = []
def check(n, c, info=""):
    R.append((n, bool(c))); print(("PASS " if c else "FAIL ") + n + ("" if c else "  -> " + str(info)[:300]))
subprocess.run(["bash", "setup.sh"], capture_output=True)
subprocess.run(["python3", "seed_demo.py"], capture_output=True)
subprocess.run(["./deploy_ui.sh"], capture_output=True)
subprocess.run(["./start_player.sh", LUA], capture_output=True); time.sleep(1)
J = Jooki()
def pl_by_title(t):
    for k, v in J.pls.items():
        if v.get("title") == t: return k
with sync_playwright() as p:
    b = p.chromium.launch()
    ctx = b.new_context(viewport={"width": 390, "height": 844}, is_mobile=True, has_touch=True, locale="fr-FR", timezone_id="Europe/Paris", bypass_csp=True)
    pg = ctx.new_page(); errs = []
    pg.on("console", lambda m: errs.append(m.text) if m.type == "error" and "ERR_CONNECTION_REFUSED" not in m.text and "ERR_CONNECTION_RESET" not in m.text else None)
    pg.on("pageerror", lambda e: errs.append("PAGEERROR " + str(e)))
    toasts = []
    pg.goto(URL + "/")
    try: pg.wait_for_selector(".pl[data-pl]")
    except Exception:
        # say why before dying: what the page got, what it said, what the core has
        print("E0 page never listed the playlists\n  console:", errs[-10:], "\n  html:", pg.content()[:1500].replace("\n", " "),
              "\n  core playlists:", sorted(J.pls), "\n  http /:", subprocess.run(["curl", "-sI", URL + "/"], capture_output=True, text=True).stdout[:200], flush=True)
        raise
    check("E0 home lists the 6 playlists", pg.locator(".pl[data-pl]").count() == 6, pg.locator(".pl[data-pl]").count())
    # E1 create
    pg.click("[data-k=newpl]"); pg.fill("[data-k=plname]", "  Histoires du soir "); pg.keyboard.press("Enter")
    pg.wait_for_url("**/#/p/*", timeout=5000)
    pid = pg.url.split("/#/p/")[1]
    J.wait(lambda: pid in J.pls)
    check("E1 playlist created and opened (trimmed name)", J.pls.get(pid, {}).get("title") == "Histoires du soir", J.pls.get(pid))
    # E2 upload from the file picker (phone path)
    pg.set_input_files("input[type=file]", ["media/song4.mp3", "media/song5.mp3", "media/notaudio.mp3", "media/garbage.mp3"])
    pg.wait_for_function("document.querySelectorAll('.up.done, .up.error').length >= 4", timeout=60000)
    done = pg.locator(".up.done").count(); err = pg.locator(".up.error").count()
    J.wait(lambda: len(J.pls[pid]["tracks"]) == 2)
    check("E2 upload: 2 added, 2 refused with a reason", done == 2 and err == 2 and len(J.pls[pid]["tracks"]) == 2, (done, err, J.pls[pid]))
    txt = pg.locator(".uploads").inner_text()
    check("E2 upload errors are explained in French", "trop petit" in txt and ("format audio" in txt), txt)
    # E3 rename
    pg.click("[data-k=renamebtn]"); pg.fill("[data-k=title]", "Histoires"); pg.keyboard.press("Enter")
    J.wait(lambda: J.pls[pid].get("title") == "Histoires")
    check("E3 rename with Enter", J.pls[pid].get("title") == "Histoires", J.pls[pid])
    # E4 character: take the Dragon (used by Pierre et le Loup) -> warning, then moved
    pierre = pl_by_title("Pierre et le Loup")
    pg.click("[data-k=tokbtn]"); pg.click("[data-char='Jooki.Dragon']")
    warn = pg.locator(".sheet .banner").inner_text()
    pg.click("[data-k=charsave]")
    J.wait(lambda: J.pls[pid].get("star") == "Jooki.Dragon")
    check("E4 moving a character warns and moves it", "Pierre et le Loup" in warn and J.pls[pid].get("star") == "Jooki.Dragon" and not J.pls[pierre].get("star"), (warn, J.pls[pid], J.pls[pierre]))
    pg.click("[data-k=tokbtn]"); pg.click("[data-char='none']"); pg.click("[data-k=charsave]")
    J.wait(lambda: not J.pls[pid].get("star"))
    check("E4 unlink character", not J.pls[pid].get("star"), J.pls[pid])
    J.send("PLAYLIST_UPDATE", {"playlist": {"id": pierre, "star": "Jooki.Dragon"}}); J.settle()
    # E5 add from library
    pg.click("text=Depuis la bibliothèque"); pg.fill("[data-k=libq]", "cygne")
    pg.locator(".sheet li").first.click()
    pg.fill("[data-k=libq]", "hémiones"); pg.locator(".sheet li").first.click()
    pg.click("[data-k=libadd]")
    J.wait(lambda: len(J.pls[pid]["tracks"]) == 4)
    names = [J.tracks[x]["title"] for x in J.pls[pid]["tracks"]]
    check("E5 add 2 tracks from the library (search)", len(names) == 4 and "Le Cygne" in names and "Hémiones" in names, names)
    # E7 remove + undo
    before = list(J.pls[pid]["tracks"])
    pg.locator("[data-remove='0']").click()
    J.wait(lambda: len(J.pls[pid]["tracks"]) == 3)
    pg.locator(".toast button").click()
    J.wait(lambda: J.pls[pid]["tracks"] == before)
    check("E7 remove then undo", J.pls[pid]["tracks"] == before, J.pls[pid]["tracks"])
    # E8 radio
    pg.click("text=Radio web"); pg.fill("[data-k=rname]", "FIP"); pg.fill("[data-k=rurl]", "fip.fr"); pg.keyboard.press("Enter")
    bad = pg.locator(".sheet .banner").inner_text()
    pg.fill("[data-k=rurl]", "https://icecast.radiofrance.fr/fip-hifi.aac"); pg.keyboard.press("Enter")
    J.wait(lambda: len(J.pls[pid]["tracks"]) == 5)
    check("E8 radio: bad URL explained, good URL added", "http" in bad and len(J.pls[pid]["tracks"]) == 5, bad)
    # E9 audiobook
    pg.click("[data-k=audiobook]"); J.wait(lambda: J.pls[pid].get("audiobook") is True)
    check("E9 audiobook toggle", J.pls[pid].get("audiobook") is True, J.pls[pid])
    # E13 play from a track row + player bar + sheet
    pg.locator("li[data-i='1']").click(); time.sleep(1.5)
    np = J.state["audio"]["nowPlaying"]
    check("E13 tap a track plays it", np.get("playlistId") == pid and np.get("trackIndex") == 2, np)
    bar = pg.locator(".player .t").inner_text()
    check("E13 player bar shows the track", bar.strip() == J.tracks[J.pls[pid]["tracks"][1]]["title"], bar)
    pg.click("[data-k=pp]"); J.wait(lambda: J.state["audio"]["playback"].get("state") == "PAUSED")
    check("E13 pause from the bar", J.state["audio"]["playback"].get("state") == "PAUSED", J.state["audio"]["playback"])
    pg.click(".player .info"); pg.wait_for_selector(".np")
    pg.click("[data-k=nppp]"); J.wait(lambda: J.state["audio"]["playback"].get("state") == "PLAYING")
    check("E13 play from the sheet", J.state["audio"]["playback"].get("state") == "PLAYING")
    pg.keyboard.press("Escape")
    # E6 reorder by drag (pointer events) on desktop-size page
    dctx = b.new_context(viewport={"width": 1200, "height": 900}, locale="fr-FR", bypass_csp=True); dp = dctx.new_page()
    dp.on("pageerror", lambda e: errs.append("PAGEERROR " + str(e)))
    dp.goto(URL + "/#/p/" + pid); dp.wait_for_selector("li[data-i='2']")
    dp.wait_for_selector("li[data-i='0'] .handle", state="visible")   # the handle renders after the row
    order = list(J.pls[pid]["tracks"])
    h0 = dp.locator("li[data-i='0'] .handle").bounding_box(); h2 = dp.locator("li[data-i='2']").bounding_box()
    dp.mouse.move(h0["x"] + 10, h0["y"] + 10); dp.mouse.down()
    for k in range(1, 11): dp.mouse.move(h0["x"] + 10, h0["y"] + 10 + (h2["y"] - h0["y"]) * k / 10)
    dp.mouse.up()
    exp = order[1:3] + order[0:1] + order[3:]
    J.wait(lambda: J.pls[pid]["tracks"] == exp)
    check("E6 drag to reorder", J.pls[pid]["tracks"] == exp, (order, J.pls[pid]["tracks"]))
    # E10 delete playlist -> tracks become unused -> delete forever
    pg.goto(URL + "/#/p/" + pid); pg.wait_for_selector("text=Supprimer la playlist")
    pg.click("text=Supprimer la playlist"); pg.click("[data-k=ok]")
    J.wait(lambda: pid not in J.pls)
    pg.wait_for_url("**/#/")
    un = J.pls.get("TRASH", {}).get("tracks", [])
    check("E10 deleting a playlist keeps its songs (in Unused)", pid not in J.pls and len(un) == 3, un)  # 2 uploads + test tone; library tracks still used
    pg.goto(URL + "/#/library/unused"); pg.wait_for_selector("li[data-track]")
    victims = [x for x in un if J.tracks[x].get("userFilename") in ("song4.mp3", "song5.mp3")]
    for v in victims: pg.locator("li[data-track='%s']" % v).click()
    pg.click("text=Supprimer du Jooki"); pg.click("[data-k=ok]")
    J.wait(lambda: all(v not in J.tracks for v in victims))
    check("E10 delete forever from Unused (files erased)", all(v not in J.tracks and not os.path.exists("/jooki/external/jooki/uploads/" + v) for v in victims), victims)
    # E11 tokens
    # the screen is a grid of tiles; a tile opens the character's sheet (playlist, tokens, names)
    pg.goto(URL + "/#/tokens"); pg.wait_for_selector("[data-char]")
    tiles = pg.locator("[data-char]").count()
    check("E11 tokens screen is tiles only (no select, no input on the page)", tiles >= 6 and pg.locator("[data-char-select]").count() == 0 and pg.locator("[data-k^='name-']").count() == 0, (tiles, pg.locator("[data-char-select]").count()))
    tag = "04000000D00002"  # unnamed dragon
    pg.click("[data-char='Jooki.Dragon']"); pg.wait_for_selector("[data-k='name-%s']" % tag)
    inp = pg.locator("[data-k='name-%s']" % tag)
    inp.fill("Dragon de Léo"); inp.press("Enter")
    J.wait(lambda: J.tokens[tag].get("name") == "Dragon de Léo")
    inp = pg.locator("[data-k='name-%s']" % tag); inp.fill("Dragon de Léo"); inp.press("Enter"); time.sleep(0.8)
    errtoast = pg.locator(".toast.error").count()
    check("E11 naming a token (twice) works, no error", J.tokens[tag].get("name") == "Dragon de Léo" and errtoast == 0, (J.tokens[tag], errtoast))
    check("E11 naming does not steal the playlist", J.pls[pierre].get("star") == "Jooki.Dragon" and not J.pls[pierre].get("tagId"), J.pls[pierre])
    pg.keyboard.press("Escape"); time.sleep(0.3)
    pg.fill("[data-k=tokq]", "léo"); time.sleep(0.4)
    check("E11 search by a token's name keeps only its character", pg.locator("[data-char]").count() == 1 and pg.locator("[data-char='Jooki.Dragon']").count() == 1, pg.locator("[data-char]").count())
    pg.fill("[data-k=tokq]", ""); time.sleep(0.4)
    tri = pl_by_title("Chansons de marins")   # started by the Knight in the seed: taking it asks first
    pg.click("[data-char='Jooki.Black.Whale']"); pg.wait_for_selector("[data-char-select='Jooki.Black.Whale']")
    pg.select_option("[data-char-select='Jooki.Black.Whale']", tri)
    pg.wait_for_selector("[data-k=ok]"); asked = pg.locator(".sheet").inner_text(); pg.click("[data-k=ok]")
    J.wait(lambda: J.pls[tri].get("star") == "Jooki.Black.Whale")
    check("E11 link a character to a playlist from the tokens page (asks when the playlist is taken)", "Chevalier" in asked and J.pls[tri].get("star") == "Jooki.Black.Whale", (asked, J.pls[tri]))
    if not pg.locator("[data-tag='04000000B00002'] button").count(): pg.click("[data-char='Jooki.Black.Whale']")   # the sheet comes back after the question
    pg.wait_for_selector("[data-tag='04000000B00002'] button")
    pg.locator("[data-tag='04000000B00002'] button").click(); pg.click("[data-k=ok]")
    J.wait(lambda: "04000000B00002" not in J.tokens)
    check("E11 forget a token keeps the character's playlist", "04000000B00002" not in J.tokens and J.pls[tri].get("star") == "Jooki.Black.Whale", J.pls[tri])
    if pg.locator(".sheet").count(): pg.keyboard.press("Escape")
    # E11b a foreign NFC tag (an amiibo): its own tile, linked like a character, then it plays
    amiibo = "046158B2661290"; fch = "tag." + amiibo
    J.nfc_foreign(amiibo); J.wait(lambda: amiibo in J.tokens)
    pg.wait_for_selector("[data-char='%s']" % fch)
    card = pg.locator("[data-char='%s'] .title" % fch).inner_text()
    check("E11b a foreign tag gets its own tile, named by the end of its id", card.strip().endswith("1290"), card)
    pg.click("[data-char='%s']" % fch); pg.wait_for_selector("[data-char-select='%s']" % fch)
    pg.select_option("[data-char-select='%s']" % fch, tri)
    pg.wait_for_selector("[data-k=ok]"); pg.click("[data-k=ok]")   # taken from the Black whale: asks
    J.wait(lambda: J.pls[tri].get("star") == fch)
    # E11c a photo for the tag: a red disc on white -> background removed in the browser -> 128 px PNG on the Jooki
    import struct, zlib
    def png(w, hgt, px):
        raw = b"".join(b"\x00" + b"".join(px(x, y) for x in range(w)) for y in range(hgt))
        def chunk(k, d): return struct.pack(">I", len(d)) + k + d + struct.pack(">I", zlib.crc32(k + d) & 0xffffffff)
        return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", w, hgt, 8, 2, 0, 0, 0)) + chunk(b"IDAT", zlib.compress(raw)) + chunk(b"IEND", b"")
    open("media/tag_photo.png", "wb").write(png(200, 160, lambda x, y: b"\xe0\x30\x20" if (x - 100) ** 2 + (y - 80) ** 2 < 55 ** 2 else b"\xff\xff\xff"))
    if not pg.locator("[data-k=photo]").count(): pg.click("[data-char='%s']" % fch)
    pg.wait_for_selector("[data-k=photo]", state="attached")
    pg.set_input_files("[data-k=photo]", "media/tag_photo.png")
    pg.wait_for_selector("[data-k=edsave]"); time.sleep(0.8)
    pg.click("[data-k=edbg]"); time.sleep(0.5)
    alpha = pg.evaluate("(function(){var c=document.querySelector('.edcanvas'),d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;var a=0;for(var i=3;i<d.length;i+=4)if(d[i]>200)a++;return a/(d.length/4);})()")
    check("E11c the background is removed in the browser (most of the frame is transparent)", 0.02 < alpha < 0.5, alpha)
    pg.click("[data-k=edsave]")
    J.wait(lambda: (J.tokens.get(amiibo) or {}).get("image"), 15)
    img = (J.tokens.get(amiibo) or {}).get("image") or ""
    path = "/jooki/external/jooki/artwork/tok_%s.png" % amiibo
    check("E11c the photo is saved on the Jooki and linked to the tag", img.startswith("/artwork/tok_%s.png?v=" % amiibo) and os.path.exists(path) and 0 < os.path.getsize(path) < 40000, (img, os.path.exists(path) and os.path.getsize(path)))
    pg.wait_for_selector("[data-char='%s'] .tok img" % fch, timeout=5000)
    check("E11c the tag's tile shows the photo", pg.locator("[data-char='%s'] .tok img" % fch).get_attribute("src").endswith(img), pg.locator("[data-char='%s'] .tok img" % fch).get_attribute("src"))
    pg.wait_for_selector("[data-k=photo-remove]", timeout=10000)   # the editor gives way to the tag's sheet again
    # a picture of the library instead of the photo: the photo's file goes
    pg.click("[data-k=libpick]"); pg.wait_for_selector(".libcell[data-img='unicorn']")
    pg.click(".libcell[data-img='unicorn']")
    J.wait(lambda: (J.tokens.get(amiibo) or {}).get("image") == "lib:unicorn")
    check("E11c a library picture replaces the photo, whose file goes", (J.tokens.get(amiibo) or {}).get("image") == "lib:unicorn" and not os.path.exists(path),
          ((J.tokens.get(amiibo) or {}).get("image"), os.path.exists(path)))
    pg.wait_for_selector("[data-k=photo-remove]", timeout=10000)
    pg.click("[data-k=photo-remove]")
    J.wait(lambda: not (J.tokens.get(amiibo) or {}).get("image"))
    check("E11c removing the picture", not (J.tokens.get(amiibo) or {}).get("image"), J.tokens.get(amiibo))
    if pg.locator(".sheet").count(): pg.keyboard.press("Escape")
    J.nfc_foreign(amiibo); J.wait(lambda: J.state["audio"]["nowPlaying"].get("playlistId") == tri)
    check("E11b the linked foreign tag starts its playlist", J.pls[tri].get("star") == fch and J.state["audio"]["nowPlaying"].get("playlistId") == tri, (J.pls[tri], J.state["audio"].get("nowPlaying")))
    # E22 flat tokens: one code (512) for all of them, but each one is its own tile; a picture from the library
    CAT, ELE = "04A1B2C3D49C41", "04A1B2C3D477A0"
    J.nfc(CAT, "200"); J.wait(lambda: CAT in J.tokens); J.nfc_off(); J.settle()
    J.nfc(ELE, "200"); J.wait(lambda: ELE in J.tokens); J.nfc_off(); J.settle()
    pg.goto(URL + "/#/tokens"); pg.wait_for_selector("[data-char='flat.%s']" % ELE)
    tcat = pg.locator("[data-char='flat.%s'] .title" % CAT).inner_text()
    check("E22 two flat tokens, two tiles, named by the end of their id", pg.locator("[data-char='flat.%s']" % ELE).count() == 1 and tcat.strip().endswith("9C41"), tcat)
    pg.click("[data-char='flat.%s']" % CAT); pg.wait_for_selector("[data-k=libpick]")
    pg.click("[data-k=libpick]"); pg.wait_for_selector(".libcell[data-img]", timeout=10000)
    ncell = pg.locator(".libcell[data-img]").count()
    check("E22 the library opens with all its pictures, by family", ncell > 600 and pg.locator(".libcats button").count() >= 10, (ncell, pg.locator(".libcats button").count()))
    pg.fill("[data-k=imgq]", "minou"); time.sleep(0.4)
    hits = pg.locator(".libcell[data-img]").evaluate_all("els => els.map(e => e.getAttribute('data-img'))")
    check("E22 the search knows children's words ('minou' finds the cats)", "cat" in hits and 0 < len(hits) <= 6 and all("cat" in x for x in hits), hits)
    pg.click(".libcell[data-img='cat']")
    J.wait(lambda: J.tokens[CAT].get("image") == "lib:cat")
    check("E22 the picture is set; the unnamed token takes its name", J.tokens[CAT].get("image") == "lib:cat" and J.tokens[CAT].get("name") == "Chat", J.tokens[CAT])
    if pg.locator(".sheet").count(): pg.keyboard.press("Escape")
    # the round token's own picture is an <img> too: wait for the library one, loaded
    pg.wait_for_function("(function(){var i=document.querySelector(\"[data-char='flat.%s'] .tok img\");return !!i && i.getAttribute('src')==='/tokimg/cat.webp' && i.complete && i.naturalWidth>0;})()" % CAT, timeout=10000)
    src = pg.locator("[data-char='flat.%s'] .tok img" % CAT).get_attribute("src")
    loaded = pg.evaluate("(function(){var i=document.querySelector(\"[data-char='flat.%s'] .tok img\");return i.complete && i.naturalWidth;})()" % CAT)
    check("E22 the tile shows the picture, served by the Jooki", src == "/tokimg/cat.webp" and loaded == 128, (src, loaded))
    import urllib.request
    with urllib.request.urlopen(URL + "/tokimg/cat.webp") as r:
        check("E22 the Jooki serves the pictures as WebP the phone may keep", r.headers.get("Content-Type") == "image/webp" and "max-age" in (r.headers.get("Cache-Control") or ""), dict(r.headers))
    # E12 settings
    pg.goto(URL + "/#/settings"); pg.wait_for_selector("[data-k=shuffle]")
    pg.click("[data-k=shuffle]"); J.wait(lambda: J.state["audio"]["config"].get("shuffle_mode") is True)
    check("E12 shuffle toggle", J.state["audio"]["config"].get("shuffle_mode") is True, J.state["audio"]["config"])
    check("E12 the settings page is short: the topics open on their own pages",
          pg.locator("[data-k=nightstart]").count() == 0 and pg.locator("[data-k=sshkey]").count() == 0 and pg.locator("a[href='#/settings/night']").count() == 1)
    pg.click("[data-k=langnav]"); pg.wait_for_url("**/#/settings/language")
    pg.click("text=English"); pg.wait_for_selector("h1:text-is('Language')")
    pg.click("a.icon-btn[href='#/settings']"); pg.wait_for_selector("h1:text-is('Settings')")
    check("E12 language switch to English, back to Settings", pg.locator("h1").inner_text() == "Settings")
    pg.goto(URL + "/#/settings/language"); pg.click("text=Français"); pg.wait_for_selector("h1:text-is('Langue')")
    # E16 update from the page (the Jooki checks GitHub itself; bench has no GitHub Pages access -> failure path)
    pg.goto(URL + "/#/settings"); pg.wait_for_selector("[data-k=verline]", timeout=15000)
    ver = pg.locator("[data-k=verline]").inner_text()
    check("E16 settings shows the installed OpenJooki version", "OpenJooki 1.0.0" in ver, ver)
    pg.wait_for_selector("[data-k=updrow]", timeout=60000)
    check("E16 the settings page offers the update first", pg.locator("[data-k=updrow]").count() == 1 and pg.locator("[data-k=updrow]").get_attribute("href") == "#/settings/update")
    pg.goto(URL + "/#/settings/update"); pg.wait_for_selector("[data-k=updnow]", timeout=60000)
    txt = pg.locator("main").inner_text()
    check("E16 a newer GitHub release is offered", "Nouvelle version" in txt, txt[-300:])
    pg.goto(URL + "/#/"); pg.wait_for_selector("[data-k=updbanner]", timeout=5000)
    check("E16 update banner on the home page", pg.locator("[data-k=updbanner]").count() == 1)
    pg.goto(URL + "/#/settings/update"); pg.wait_for_selector("[data-k=updnow]")
    pg.click("[data-k=updnow]"); pg.click("[data-k=ok]")
    pg.wait_for_selector("text=Mise à jour en cours", timeout=5000)
    pg.wait_for_selector("text=n'a pas pu se faire", timeout=90000)
    check("E16 update start: progress shown, failure reported clearly (no GitHub Pages here)", True)
    # E17 bedtime settings (the page also sends the browser's time zone)
    pg.goto(URL + "/#/settings/night"); pg.wait_for_selector("[data-k=bedcard]")
    J.wait(lambda: J.state.get("bedtime", {}).get("cfg", {}).get("tzbase") is not None)
    txt = pg.locator("[data-k=bedcard]").inner_text()
    check("E17 night mode shown with its defaults", "Mode nuit" in txt and pg.locator("[data-k=nightstart]").input_value() == "20:00"
          and pg.locator("[data-k=nightstop]").input_value() == "07:00" and pg.locator("[data-k=nighttimer]").input_value() == "20", txt[:200])
    pg.fill("[data-k=nightstart]", "19:45"); pg.locator("[data-k=nightstart]").dispatch_event("change")
    pg.select_option("[data-k=nighttimer]", "30")
    J.wait(lambda: J.state["bedtime"]["cfg"]["start"] == 19 * 60 + 45 and J.state["bedtime"]["cfg"]["timer"] == 30)
    check("E17 start time and automatic timer changed from the page", J.state["bedtime"]["cfg"]["start"] == 1185 and J.state["bedtime"]["cfg"]["timer"] == 30, J.state["bedtime"]["cfg"])
    check("E17 time zone sent by the page (Paris)", J.state["bedtime"]["cfg"]["tzbase"] == 60 and J.state["bedtime"]["cfg"]["tzdst"] == "EU", J.state["bedtime"]["cfg"])
    pg.click("[data-k=nighton]"); J.wait(lambda: J.state["bedtime"]["cfg"]["enabled"] is False)
    pg.wait_for_selector("[data-k=nightstart]", state="detached", timeout=5000)
    check("E17 night mode can be turned off", J.state["bedtime"]["cfg"]["enabled"] is False and pg.locator("[data-k=nightstart]").count() == 0)
    pg.click("[data-k=nighton]"); J.wait(lambda: J.state["bedtime"]["cfg"]["enabled"] is True)
    # E18 sleep timer from the player
    comp = pl_by_title("Comptines 2")
    J.send("PLAYLIST_PLAY", {"playlistId": comp}); J.wait(lambda: J.state["audio"]["playback"].get("state") == "PLAYING")
    pg.goto(URL + "/#/"); pg.click(".player .info"); pg.wait_for_selector("[data-sleep-min='20']")
    pg.click("[data-sleep-min='20']")
    J.wait(lambda: (J.state["bedtime"].get("sleep") or {}).get("total") == 1200)
    pg.wait_for_function("document.querySelector('[data-sleep]') && /Arrêt dans (20:00|19:)/.test(document.querySelector('[data-sleep]').textContent)", timeout=5000)
    check("E18 20-minute timer started, countdown shown", (J.state["bedtime"].get("sleep") or {}).get("total") == 1200)
    check("E18 moon + countdown in the player bar", pg.locator(".player .sleepmini").count() == 1)
    pg.click("[data-k=sleepoff]"); J.wait(lambda: not J.state["bedtime"].get("sleep"))
    pg.wait_for_selector(".player .sleepmini", state="detached", timeout=5000)
    check("E18 timer cancelled", not J.state["bedtime"].get("sleep") and pg.locator(".player .sleepmini").count() == 0)
    pg.click("[data-sleep-min='track']"); J.wait(lambda: (J.state["bedtime"].get("sleep") or {}).get("mode") == "track")
    pg.wait_for_selector("text=Arrêt à la fin de ce morceau")
    check("E18 'end of chapter' timer", True)
    pg.click("[data-k=sleepoff]"); pg.keyboard.press("Escape")
    # E19 audiobook: put the chapters back in order, resume shown, start again
    pierre = pl_by_title("Pierre et le Loup")
    shuffled = list(reversed(J.pls[pierre]["tracks"]))
    J.send("PLAYLIST_UPDATE", {"playlist": {"id": pierre, "tracks": shuffled, "audiobook": True}}); J.wait(lambda: J.pls[pierre]["tracks"] == shuffled)
    pg.goto(URL + "/#/p/" + pierre); pg.wait_for_selector("[data-k=sortbtn]")
    pg.click("[data-k=sortbtn]"); pg.wait_for_selector("[data-k=sortby-title]")
    pg.click("[data-k=sortby-title]"); pg.click("[data-k=sortok]")
    J.wait(lambda: J.pls[pierre]["tracks"] != shuffled)
    titles = [J.tracks[x]["title"] for x in J.pls[pierre]["tracks"]]
    check("E19 'sort by title' puts the chapters back in order", titles == sorted(titles, key=str.lower), titles)
    # the same criterion twice reverses the order; the preview and the button follow
    pg.click("[data-k=sortbtn]"); pg.wait_for_selector("[data-k=sortby-title]")
    pg.click("[data-k=sortby-title]"); pg.click("[data-k=sortby-title]"); pg.click("[data-k=sortok]")
    J.wait(lambda: [J.tracks[x]["title"] for x in J.pls[pierre]["tracks"]] == sorted(titles, key=str.lower, reverse=True))
    check("E19 second tap reverses the order", True)
    pg.click("[data-k=sortbtn]"); pg.wait_for_selector("[data-k=sortby-title]")
    pg.click("[data-k=sortby-title]"); pg.click("[data-k=sortok]")
    J.wait(lambda: [J.tracks[x]["title"] for x in J.pls[pierre]["tracks"]] == sorted(titles, key=str.lower))
    J.send("PLAYLIST_PLAY", {"playlistId": pierre, "trackIndex": 3}); J.wait(lambda: J.state["audio"]["nowPlaying"].get("trackIndex") == 3)
    J.send("SEEK", {"position_ms": 65000}); time.sleep(1.5); J.send("DO_PAUSE", {})
    pg.wait_for_function("document.querySelector('[data-k=resume]') && /chapitre 3 · 0:5/.test(document.querySelector('[data-k=resume]').textContent)", timeout=8000)
    rtxt = pg.locator("[data-k=resume]").inner_text()
    check("E19 resume shown: chapter 3 at 0:50", "chapitre 3" in rtxt and "0:5" in rtxt, rtxt)
    pg.click("[data-k=resumereset]"); pg.wait_for_selector("text=Reprendra au chapitre 1")
    check("E19 start again from the beginning", pierre not in (J.state["bedtime"].get("resume") or {}))
    # E20 weak Wi-Fi: the transfer is cut twice, then goes through on its own
    comp = pl_by_title("Comptines 3"); n0 = len(J.pls[comp]["tracks"])
    cuts = {"n": 0, "max": 2}
    def flaky(route):
        if cuts["n"] < cuts["max"]: cuts["n"] += 1; route.abort("connectionreset")
        else: route.continue_()
    pg.route("**/upload", flaky)
    pg.goto(URL + "/#/p/" + comp); pg.wait_for_selector("input[type=file]", state="attached")
    pg.set_input_files("input[type=file]", ["media/song6.mp3"])
    pg.wait_for_selector("text=nouvel essai", timeout=10000)
    pg.wait_for_selector(".up.done", timeout=60000)
    J.wait(lambda: len(J.pls[comp]["tracks"]) == n0 + 1)
    check("E20 upload cut twice by the network: retried on its own and added once", cuts["n"] == 2 and len(J.pls[comp]["tracks"]) == n0 + 1, (cuts, len(J.pls[comp]["tracks"])))
    cuts.update(n=0, max=4)
    pg.set_input_files("input[type=file]", ["media/song3.mp3"])
    pg.wait_for_selector("[data-k^=upretry]", timeout=90000)
    check("E20 still failing after 4 tries: clear error + 'Réessayer'", cuts["n"] == 4 and pg.locator(".up.error").count() >= 1)
    pg.locator("[data-k^=upretry]").first.click()
    pg.wait_for_function("document.querySelectorAll('.up.done').length >= 2", timeout=60000)
    J.wait(lambda: len(J.pls[comp]["tracks"]) == n0 + 2)
    check("E20 'Réessayer' sends it", len(J.pls[comp]["tracks"]) == n0 + 2, len(J.pls[comp]["tracks"]))
    pg.unroute("**/upload")
    # E21 Wi-Fi quality in the settings
    J.c.publish("/j/esp32/input/net/sta/config", json.dumps({"ssid": "Box", "signal": -84, "stat": "success", "ip": "10.0.0.2"}))
    pg.goto(URL + "/#/settings/wifi"); pg.wait_for_selector("[data-k=wifiq]", timeout=15000)
    wt = pg.locator("[data-k=wifirow]").inner_text()
    check("E21 weak Wi-Fi explained, with advice", "Signal faible" in wt and "Rapprochez" in wt and "-84 dBm" in wt, wt)
    J.c.publish("/j/esp32/input/net/sta/config", json.dumps({"ssid": "Salon", "signal": -42, "stat": "success", "ip": "10.0.0.2"}))
    pg.wait_for_function("document.querySelector('[data-k=wifiq]') && /Signal bon/.test(document.querySelector('[data-k=wifiq]').textContent)", timeout=15000)
    check("E21 good Wi-Fi shown as good", "Rapprochez" not in pg.locator("[data-k=wifirow]").inner_text())
    check("E21 address shows the .local name", "jooki-bench.local" in pg.locator("main").inner_text())
    bt = pg.locator("[data-k=wifibt]")
    check("E21 the way back over Bluetooth is said, with the Jooki's Bluetooth name and the page's link",
          bt.count() == 1 and "JOOKI2_BENCH" in bt.inner_text() and "Bluetooth" in bt.inner_text()
          and bt.locator("a").get_attribute("href") == "https://guillain-rdcde.github.io/OpenJooki/wifi.html" and bt.locator("a").get_attribute("target") == "_blank",
          bt.inner_text() if bt.count() else "no line")
    # E14 offline / reconnect
    subprocess.run(["pkill", "-f", "^mosquitto -c"]); time.sleep(2.5)
    off = pg.locator(".conn").inner_text()
    subprocess.Popen(["mosquitto","-c","mosquitto.conf"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, start_new_session=True); time.sleep(1)
    subprocess.run(["./start_player.sh", LUA], capture_output=True)
    pg.wait_for_function("document.querySelector('.conn') && document.querySelector('.conn').classList.contains('on')", timeout=20000)
    check("E14 shows offline and reconnects by itself", "Hors ligne" in off and pg.locator(".conn").inner_text().strip() == "Connecté", off)
    check("E15 no JavaScript errors", not errs, errs)
    b.close()
bad = [n for n, ok in R if not ok]
print("\n%d/%d passed" % (len(R) - len(bad), len(R))); sys.exit(1 if bad else 0)
